# Generated by Django 5.1.7 on 2025-05-27 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_livro_categoria_livro_editora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.categoria'),
        ),
    ]
